#Persistent Volume Claim for MongoDB
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  labels:
    app: mongodb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi